# .github/release.yml
changelog:
  exclude:
    labels:
      - ignore for release
  categories:
    - title: New Features
      labels:
        - kind/feature
    - title: Refactor
      labels:
        - kind/enhancement
    - title: Bug Fixes
      labels:
        - kind/bug
    - title: Other Changes
      labels:
        - '*'
