# check.yml runs checks to maintain consistency
name: check

on: [pull_request, workflow_dispatch]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: Format checks
        run: |
          yarn install
          yarn run prettier:check
