# This yml is adapted from pull_request_test_build.yml
name: check

on: [pull_request, workflow_dispatch]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Format checks
        run: |
          yarn install
          yarn run prettier:check
